Add a solution of lection-03-modal
js-tasks-ru/htmlcss-20230911-4_marat-shagiev pull request #10
Opened 2023-09-26 19:29 UTC by dumbm1

Тут все было легко и приятно ))

2023-09-26 19:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-27 20:48 UTC, GSemikozov requested changes

2023-09-27 20:48 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +			<div class="modal__page-blocker"></div>
лишний элемент

2023-09-27 20:48 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +				<svg id="modal-close" class="modal__close-trigger" width="16" height="16" viewBox="0 0 16 16"
modal__close

2023-09-27 20:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> + font-family: Inter, sans-serif;
именно здесь фиксед + полупрозначный фон через rgba + растягиваем на весь вьюпорт

2023-09-27 20:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> + position: fixed;
а вот окно уже позиционируем через absolute

2023-09-27 20:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__page-blocker {
лишний элемент

2023-09-28 17:35 UTC, dumbm1 commented on 05-lection3/02-modal/index.html
> +			<div class="modal__page-blocker"></div>
убрал

2023-09-28 17:35 UTC, dumbm1 commented on 05-lection3/02-modal/index.html
> +				<svg id="modal-close" class="modal__close-trigger" width="16" height="16" viewBox="0 0 16 16"
поправил

2023-09-28 17:35 UTC, dumbm1 commented on 05-lection3/02-modal/modal.css
> + position: fixed;
сделал

2023-09-28 17:36 UTC, dumbm1 commented on 05-lection3/02-modal/modal.css
> +.modal__page-blocker {
удалил, спасибо!

2023-09-28 21:14 UTC, GSemikozov approved these changes

2023-09-28 21:14 UTC, merged