Add svg-sprite, add icon from sprite to accordion, tooltip and modal
js-tasks-ru/htmlcss-20230911-4_marat-shagiev pull request #17
Opened 2023-10-15 23:38 UTC by dumbm1

Добавил svg-спрайт с иконками для трех компонентов: `tooltip`, `accordion`, `modal`.
В этих компонентах заменил иконки на иконки из спрайта.
В аккордеоне анимировал стрелку.

Проблемы:
В аккордеон не смог вставить иконку из спрайта через псевдо-элементы `befor` или `after`.
В аккордеоне не смог анимировать раскрытие и закрытие элемента.

2023-10-15 23:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-22 19:04 UTC, GSemikozov requested changes

2023-10-22 19:04 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> + animation: opn .2s ease-in-out;
намного проще просто реализовать через transition

2023-10-31 09:13 UTC, GSemikozov approved these changes

2023-10-31 09:13 UTC, merged