Lection 05 input
js-tasks-ru/htmlcss-20230911-4_marat-shagiev pull request #22
Opened 2023-10-25 21:54 UTC by dumbm1

Решения для поля воода.

2023-10-25 22:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-31 09:28 UTC, GSemikozov requested changes

2023-10-31 09:28 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +			<span class="input__message">Все отлично</span>
а что это за message? такого нет в дизайне)

2023-10-31 09:28 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +			<label class="input__label">
в случае с инпутом все заворачивать в label не надо

2023-10-31 09:28 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +				<h2 class="input__title">Label</h2>
на уровне блока h2 не надо использовать, на самом деле - это как раз label

2023-10-31 09:28 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +			<span class="input__message input__message_success">Все отлично</span>
модификатор будет использовать один общий, причем на уровне блока, а не на уровне его элементов

2023-10-31 14:47 UTC, dumbm1 commented on 07-lection5/04-input/index.html
> +			<span class="input__message">Все отлично</span>
Изменил класс на `input__validation-info`.

Я понял из эфира, наша задача была показать пользователю какое-то информативное сообщение о том, что все идет нормально, либо ненормально и надо исправить ошибку.

И мы обсуждали, что сообщение об ошибке надо показать сразу же, как с `input` пропал фокус, чтобы пользователь не успел далеко уйти и тут же исправил ошибку.

Как пример мы должны были использовать `bootstrap`. А там как раз сообщения под каждым полем `input`.

Я для верности глянул готовый [проект](url="https://course-htmlcss.javascript.ru/formgroup.html") - в нем ведь тоже, вроде есть сообщение под каждым полем (кроме не тронутого).

Убрать, конечно, совсем не проблема, если я не правильно истолковал задачу ))

2023-10-31 14:48 UTC, dumbm1 commented on 07-lection5/04-input/index.html
> +			<label class="input__label">
поправил, спасибо)

2023-10-31 14:48 UTC, dumbm1 commented on 07-lection5/04-input/index.html
> +				<h2 class="input__title">Label</h2>
поправил, спасибо)

2023-10-31 14:50 UTC, dumbm1 commented on 07-lection5/04-input/index.html
> +			<span class="input__message input__message_success">Все отлично</span>
Все переделал, Герман, спасибо большое за комменты!

2023-11-01 16:51 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +			<span class="input__message">Все отлично</span>
нет, поскольку этого в дизайне нет, то и самостоятельно додумывать не стоит

2023-11-01 16:52 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +			<span class="input__message">Все отлично</span>
речь была про best practices в целом, но - работа с ошибками закладывается изначально на уровне дизайна

2023-11-01 19:49 UTC, GSemikozov approved these changes

2023-11-01 19:49 UTC, merged