Lection 05 radio
js-tasks-ru/htmlcss-20230911-4_marat-shagiev pull request #24
Opened 2023-10-25 22:07 UTC by dumbm1

Решение для радио-кнопок

2023-10-25 22:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-25 22:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-31 09:26 UTC, GSemikozov requested changes

2023-10-31 09:26 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +							<use href="../../assets/images/icons-sprite.svg#radio"></use>
кружок ведь можно отрисовать просто через css)

2023-10-31 13:25 UTC, dumbm1 commented on 07-lection5/02-radio/index.html
> +							<use href="../../assets/images/icons-sprite.svg#radio"></use>
поправил, спасибо!

2023-11-01 16:51 UTC, GSemikozov approved these changes

2023-11-01 16:51 UTC, merged