Lection 05 tabs
js-tasks-ru/htmlcss-20230911-4_marat-shagiev pull request #26
Opened 2023-10-29 11:27 UTC by dumbm1

**Табы на главной странице.**

Чтобы добавить табы поправил верстку:
- Отделил h1-заголовок страницы от шапки - для этого создал отдельный компонент `h1`.
- Сделал для SEO h1-заголовок внутренней страницы компонента и скрыл - `{position: absolute; left: -10000px;}`.

Сверстал табы - идея в учебнике + подсказка в видео + совет преподавтеля в чате.

Был вопрос: как же показать, что табы в фокусе?
Решил так: когда `radio` в фокусе, то его текст черный.

2023-10-29 11:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-30 20:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-31 10:03 UTC, GSemikozov requested changes

2023-10-31 10:03 UTC, GSemikozov commented on components/h1/h1.css
> +.h1__title {
элемент заголовок в блоке h1? здесь явно какая-то семантическая ошибка)
да и нет смысла выносить

2023-10-31 13:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-31 14:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-31 15:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-01 16:53 UTC, GSemikozov approved these changes

2023-11-01 16:53 UTC, merged