Lection 07 task2
js-tasks-ru/htmlcss-20230911-4_marat-shagiev pull request #28
Opened 2023-11-10 12:23 UTC by dumbm1

**Разместил все компоненты по карточкам**

Отрефакторил `css` всех компонентов: поменял `px` на относительные еденицы измерения `em` и `%`.
Добавил адаптив.

_Не понял, что размещать в табе `Templates`_

За простой формулировкой задачи №2 лекции №7 прячется одно из самых сложных и запутанных заданий курса  %\  )))

2023-11-10 12:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-12 14:17 UTC, GSemikozov requested changes

2023-11-12 14:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn_preview{
это лишнее, используем стандартную primary

2023-11-12 14:17 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> + width: 100%;
точно надо?)

2023-11-12 14:17 UTC, GSemikozov commented on components/container/container.css
> +.container_preview_inputs {
в целом по всему МР-у я бы советовал не заморачиваться с этими штуками (для каждого компонента писать свои модификаторы на каждом уровне встраивания, то очень не универсально). Достаточно использовать например на уровне карточки общий элемент для встраивания, а если есть необходимость например ограничить по ширине сам блок - то тогда через модификатор этого блока.

2023-11-29 08:10 UTC, closed without merging

2023-11-29 08:11 UTC, dumbm1 commented
этот ПР уже не нужен, потому что я разбил его на кучку маленьких ПР и они почти все приняты