Lection 07 task2 tooltip
js-tasks-ru/htmlcss-20230911-4_marat-shagiev pull request #30
Opened 2023-11-16 19:53 UTC by dumbm1

Решена часть второй задачи из лекции 7 - компонент `tooltip`:

- Переписал `tooltip`: заменил `px `на `em`.
- Создал лишь один модификатор для демонстрации подсказки на главной странице.
- Встроил компонент в первую карточку.
- Для мобильных: в карточке уменьшаю шрифт через медиа-запрос и компонент автоматически уменьшается.

2023-11-16 19:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-16 23:30 UTC, GSemikozov requested changes

2023-11-16 23:30 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> + font-size: 1em;
на уровне блока мы точно всегда будем уверены чему равен 1em?)
чаще на уровне блока у нас все-таки rem | px

2023-11-17 10:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-17 10:55 UTC, dumbm1 commented on 05-lection3/01-tooltip/tooltip.css
> + font-size: 1em;
Эх, а я думал, что в том и заключается универсальность компонента - не важно, что снаружи, внутри будут сохраняться пропорции.

И показалось классным, что за точный размер шрифта отвечает внешний контейнер, куда будем компонент вставлять...

Значит так лучше не делать?

Исправил, спасибо )))

2023-11-18 21:16 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> + font-size: 1em;
Значит так лучше не делать? ==> это зависит от того, как строим систему; на самом деле можно сделать и так, как реализовано сейчас.)

2023-11-18 21:17 UTC, GSemikozov approved these changes

2023-11-18 21:17 UTC, merged