Added rem-em units to avatar. Inserted avatar to the card in the main…
js-tasks-ru/htmlcss-20230911-4_marat-shagiev pull request #34
Opened 2023-11-20 20:25 UTC by dumbm1

Добавил аватар в карточку на главную.
Размеры аватара переделал на относительные.
Пофиксил размер мобильной карточки - размер внутренней части с контентом отличался от размера в фигме.

2023-11-20 20:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-20 20:52 UTC, GSemikozov approved these changes

2023-11-20 20:52 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-11-20 20:52 UTC, GSemikozov requested changes
надо исправить конфликт

2023-11-21 04:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-21 05:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-21 05:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-21 10:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-22 10:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-22 10:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-23 20:56 UTC, GSemikozov approved these changes, later dismissed

2023-11-23 20:56 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-11-23 21:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-12-02 20:54 UTC, GSemikozov approved these changes

2023-12-02 20:54 UTC, merged