Lection 01 accordeon
js-tasks-ru/htmlcss-20230911-4_marat-shagiev pull request #6
Opened 2023-09-20 19:26 UTC by dumbm1

Аккардеон, начало.

- Добавил БЭМ-классы и текст в разметку компонента.
- Импортировал шрифт Inter.
- Добавил стили из Фигмы.
- Убрал дефолтную стрелку.

2023-09-20 19:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-20 20:16 UTC, GSemikozov requested changes

2023-09-20 20:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> + max-width: 1200px; /*demo-option*/
лишнее

2023-09-20 20:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> + padding: 20px; /*demo-option*/
лишнее

2023-09-20 20:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> + font: inherit;
лишнее

2023-09-20 20:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> + font: inherit;
лишнее

2023-09-21 05:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-21 20:19 UTC, GSemikozov requested changes

2023-09-21 20:19 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> + font: 400 16px/1.5 Inter, sans-serif;
не надо) просто заменить `*` на body в main.css

2023-09-22 03:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-22 13:04 UTC, GSemikozov approved these changes

2023-09-22 13:04 UTC, merged